### ISSUE TITLE
Error when testing toolbox in ArcMap

### ISSUE THREAD

**Issue by HEdingfield** [Geosyntec/python-tidegates#37]
See this screenshot for parameters I specified and the error log:
![tidegate_error_201511101613](https://cloud.githubusercontent.com/assets/8259446/11080266/224a1552-87c7-11e5-9493-61586b551398.png)

**Comment by HEdingfield** [comment]
The above error no longer occurs, but I'm getting a new one now when I run with the same parameters.

![issue37-2](https://cloud.githubusercontent.com/assets/8259446/11198241/29d6934e-8c78-11e5-92c5-957012a2705e.png)

**Comment by HEdingfield** [comment]
Note that I encounter this error when using both "1 - Create Flood Scenarios" and "2 - Evaluate all standard scenarios". It occurs whether or not I include an extension in the output filename or not (e.g. output_temp.shp or output_temp.tif).

**Comment by HEdingfield** [comment]
Attempted to rectify by playing with
    `_p2r_outfile = os.path.join(arcpy.env.workspace, "_temp_pgon_as_rstr.tif")`
in `tidegates.py`, but neither .img nor using no extension fixed the problem.

**Comment by phobson** [comment]
Addressed the above in https://github.com/Geosyntec/python-tidegates/commit/f6cf2d606bc2361b470bf63bb394d6f86ddd0363

**Comment by phobson** [comment]
Hey see if #42 took care of this. I was seeing the same thing. 99% sure I fixed it.

**Comment by HEdingfield** [comment]
New error now:

    Messages
    Executing: Flooder C:\Users\HEdingfield.GEOSYNTEC\Desktop\temp\MB_Cape.gdb C:\Users\HEdingfield.GEOSYNTEC\Desktop\temp\MB_Cape.gdb\dem_x08    C:\Users\HEdingfield.GEOSYNTEC\Desktop\temp\MB_Cape.gdb\ZOI GeoID 5;10 output_flood_temp # # # #
    Start Time: Tue Nov 17 08:39:24 2015
    Running script Flooder...

    Analyzing flood elevation: 5.0 ft
    ---------------------------------

    Traceback (most recent call last):
      File "H:\Dev\PyCharm Projects\python-tidegates\tidegates\toolbox.py", line 177, in execute
        self.main_execute(**params)
      File "H:\Dev\PyCharm Projects\python-tidegates\tidegates\toolbox.py", line 780, in main_execute
        **params
      File "H:\Dev\PyCharm Projects\python-tidegates\tidegates\toolbox.py", line 662, in analyze
        asMessage=True
    TypeError: flood_area() takes at least 4 arguments (4 given)

    Failed to execute (Flooder).
    Failed at Tue Nov 17 08:39:24 2015 (Elapsed Time: 0.22 seconds)

**Comment by phobson** [comment]
closing this as it #45 seems to cover it
